services:
  financial-assistant:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./financial_assistant.db
    env_file:
      - .env
    volumes:
      - ./data:/app/data:ro
      - app_data:/app/database
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  app_data:
